ALTER TABLE generated_clips
    ADD COLUMN IF NOT EXISTS retention_score INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS emotion_score INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS clarity_score INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS pacing_score INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS payoff_score INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS loop_score INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS standalone_context_score INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS overall_score INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS suggested_title VARCHAR(300),
    ADD COLUMN IF NOT EXISTS suggested_description TEXT,
    ADD COLUMN IF NOT EXISTS suggested_hashtags TEXT
